apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
  labels:
    app: web2
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: emptydir-volume
      mountPath: /mnt /data  # Path inside the container where the volume is mounted
  volumes:
  - name: emptydir-volume
    emptyDir: {}  # Define the EmptyDir volume

