apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-web2
spec:
  containers:
    - name: my-container
      image: nginx
      volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/
  volumes:
    - name: config-volume
      configMap:
        name: my-configmap

