apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
      readOnly: true  # Mount the volume as read-only
  volumes:
  - name: secret-volume
    secret:
      secretName: my-secret  # The name of the Secret to mount


