apiVersion: v1
kind: Pod
metadata:
  name: nginx-website-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-app
    image: murshi
    imagePullPolicy: Never
    ports:
      - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: pod-nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80         # Port on which the Service will be exposed
      targetPort: 80   # Port on which the Pod is listening
      nodePort: 32533  # NodePort range is typically between 30000-32767
  type: NodePort      # Exposes the service on a NodePort

