apiVersion: v1
kind: Pod
metadata:
  name: website-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: website-storage
          mountPath: /usr/share/nginx/html  # Nginx serving files here
  volumes:
    - name: website-storage
      persistentVolumeClaim:
        claimName: website-pvc  # Mount the PVC into the Pod 
