apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi   # Size of the volume
  accessModes:
    - ReadWriteOnce   # Access mode (can be ReadWriteMany, ReadOnlyMany, etc.)
  persistentVolumeReclaimPolicy: Retain  # Policy for reclaiming the PV after release (Retain, Recycle, Delete)
  storageClassName: standard  # The storage class to use (can be left out if not needed)
  hostPath:  # For local storage on the node (typically used in non-production environments)
    path: /mnt/data/nginx-website
