apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 80   # Port on the Pods
      nodePort: 30007  # Static port on each node (accessible externally)
  type: NodePort   
